[connections.snowflake]
account = "KGVIPXS-BIB01034"
account = "KGVIPXS-BIB01034"
user = "xxx"
password = "xxxxx"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
