[default]
account = "KGVIPXS-BIB01034"
user = "CATL"
password = "16Snowsnowball10!"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
